# Generated by Django 5.1.2 on 2024-12-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_done_delete_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workouts.set'),
        ),
    ]
