# Generated by Django 5.1.2 on 2024-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='all_weights',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
