# Generated by Django 5.1.2 on 2024-12-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_routine_all_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
