# Generated by Django 5.1.2 on 2024-11-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/images/exercises/')),
                ('video_link', models.URLField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='media/videos/')),
                ('workout_category', models.CharField(choices=[('home', 'Home Workout'), ('club', 'Club Workout'), ('both', 'Home and Club Workouts')], max_length=30)),
                ('exercise_category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], max_length=30)),
                ('equipment_category', models.CharField(choices=[('none', 'No Equipment'), ('machine', 'Machine'), ('both', 'Both')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
    ]
